ClassLength:
  Enabled: false
MethodLength:
  Enabled: false
MultilineBlockChain:
  Enabled: false
BlockNesting:
  Enabled: false
Documentation:
  Enabled: false
LineLength:
  Max: 120
CyclomaticComplexity:
  Max: 10
